AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SnapshotID:
    Type: String
  S3BucketToolsName:
    Type: String
Resources:

  GitHubCallQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::AccountId}-${AWS::Region}-GitHubCallQueue.fifo"
      VisibilityTimeout: 900
      FifoQueue: True
      ContentBasedDeduplication: True
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt GitHubDeadLetterQueue.Arn
        maxReceiveCount: 3


  GitHubDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: True
      QueueName: !Sub "${AWS::AccountId}-${AWS::Region}-GitHubCallDeadLetterQueue.fifo"
      ContentBasedDeduplication: True

  ProcessGithubCallsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref S3BucketToolsName
        S3Key: !Sub "snapshot/snapshot-${SnapshotID}/lambda.zip"
      Handler: github_worker_lambda.lambda_handler
      Role: !GetAtt BatchLambdaRole.Arn
      Runtime: python3.7
      Timeout: 360
      ReservedConcurrentExecutions: 1
      MemorySize: 512
      Environment:
        Variables:
          QUEUE_URL: !Ref GitHubCallQueue
          GITHUB_QUEUE_NAME: !GetAtt GitHubCallQueue.QueueName

  BatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Batch state change rule"
      ScheduleExpression: cron(0/1 * * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt ProcessGithubCallsLambda.Arn
          Id: "BatchStateChange"

  BatchEventPolicy:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProcessGithubCallsLambda
      Principal: events.amazonaws.com
      SourceArn: !GetAtt BatchEventRule.Arn

  BatchLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "batch-lambda-policy-${AWS::Region}"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
              - Action:
                  - batch:DescribeJobQueues
                  - batch:DescribeJobDefinitions
                  - batch:SubmitJob
                  - batch:ListJobs
                Effect: Allow
                Resource: "*"
              - Action:
                  - cloudwatch:PutMetricData
                Effect: Allow
                Resource: "*"
              - Action:
                  - sqs:*
                Effect: Allow
                Resource: "*"
Outputs:
  GithubQueueUrl:
    Value: !Ref  GitHubCallQueue
    Export:
      Name: GithubQueueUrl
